apiVersion: apps/v1
kind: Deployment
metadata:
  name: goazure
spec:
  replicas: 3
  selector:
    matchLabels:
      name: goazure
  template:
    metadata:
      labels:
        name: goazure
    spec:
      containers:
      - image: kiranbabycontainerreg.azurecr.io/kiranbabycontainerrepo:goazure
        name: kiranbabycontainerreg
        ports:
          - containerPort: 8081
      imagePullSecrets: 
      - name: goazuresecret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: goazure+service
spec:
  type: LoadBalancer
  selector:
    name: goazure
  ports:
  - name: http  
    port: 80
    targetPort: 8081
